set_property SRC_FILE_INFO {cfile:C:/Users/artem/.Xilinx/project_6_2/project_6_2.srcs/constrs_1/new/lab_6_2.xdc rfile:../../../project_6_2.srcs/constrs_1/new/lab_6_2.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {dout}]
